const playlists =
{
    "s-tier":
    [
        "2Pac - Changes ft. Talent.mp3",
        "ABBA - Dancing Queen (Official Music Video).mp3",
        "Al Stewart - Year of the Cat (Official Audio).mp3",
        "Billy Joel - Modern Woman (Audio).mp3",
        "Billy Joel - Pressure (Official Video).mp3",
        "Billy Joel - Stiletto (Audio).mp3",
        "Blondie - Heart Of Glass.mp3",
        "Bon Jovi - Wanted Dead Or Alive (Official Music Video).mp3",
        "Bonnie Tyler - Holding Out For A Hero (Official HD Video).mp3",
        "Daft Punk - Get Lucky (Official Audio) ft. Pharrell Williams, Nile Rodgers.mp3",
        "David Bowie - Starman (Official Video) [4K].mp3",
        "Dexys Midnight Runners, Kevin Rowland - Come On Eileen (1982 Version).mp3",
        "Don McLean - American Pie (Lyric Video).mp3",
        "Eagles - New Kid In Town (Official Audio).mp3",
        "Fleetwood Mac - The Chain (Official Music Video) [HD].mp3",
        "Gordon Lightfoot - Sundown (Official Audio).mp3",
        "Gordon Lightfoot - Carefree Highway (1974).mp3",
        "Lenny Kravitz - Fly Away (Official Music Video).mp3",
        "MACKLEMORE & RYAN LEWIS - DOWNTOWN (OFFICIAL MUSIC VIDEO).mp3",
        "Merlin's Time - Al Stewart (studio).mp3",
        "Nickelback - How You Remind Me [OFFICIAL VIDEO].mp3",
        "Olivia Rodrigo - vampire (Official Video).mp3",
        "Pearl Jam - Jeremy (Official 4K Video).mp3",
        "Red Hot Chili Peppers - Californication (Official Music Video) [HD UPGRADE].mp3",
        "Tears For Fears - Everybody Wants To Rule The World (Official Music Video).mp3",
        "Jackson Browne - The Fuse.mp3",
        "Jackson Browne - The Pretender.mp3",
        "Dire Straits - Sultans Of Swing (Official Music Video).mp3",
        "Blue Oyster Cult - The Reaper.mp3",
        "Blue Oyster Cult - Burning For You.mp3",
        "Tom Cochrane - Life is a Highway.mp3",
    ],
    "a-tier":
    [
        "ABBA - Gimme! Gimme! Gimme! (A Man After Midnight).mp3",
        "Fleetwood Mac - Dreams (Official Audio).mp3",
        "Gordon Lightfoot - Wreck Of The Edmund Fitzgerald (Official Audio).mp3",
        "Jamiroquai - Virtual Insanity (Official Video).mp3",
        "Nirvana - Lithium (Official Music Video).mp3",
        "Pearl Jam - Even Flow (Official Video).mp3",
        "Radiohead - Karma Police.mp3",
        "Stone Temple Pilots - Creep (Official Music Video).mp3",
        "Foo Fighters - All My Life (Official HD Video).mp3",
        "Foo Fighters - The Pretender.mp3",
        "Elton John - Goodbye Yellow Brick Road.mp3",
        "George Ezra - Budapest (Official Video).mp3",
        "Jackson Browne ~ Doctor, My Eyes 1972 (Official Promo) (Upgraded to stereo) (w_lyrics) [HD].mp3",
        "Jackson Browne - For America.mp3",
        "Billy Joel - Scenes from an Italian Restaurant (Audio).mp3",
        "Billy Joel - Sleeping with the Television On (Audio).mp3",
        "Eagles - One Of These Nights (Official Audio).mp3",
        "Don Henley - The Boys Of Summer.mp3",
        "Glenn Frey - You Belong To The City.mp3",
        "Sting - Be Still My Beating Heart.mp3",
        "Pearl Jam - Black (Official Audio).mp3",
        "Stompin' Tom Connors - Bud The Spud.mp3",
        "Foster The People - Lotus Eater (Audio).mp3",
        "The Smashing Pumpkins - 1979 (Official Music Video).mp3",
        "David Bowie - Young Americans.mp3",
        "David Bowie - Modern Love (Official Video) [HD].mp3",
        "Al Stewart - Night Train to Munich.mp3",
        "George Michael - Faith.mp3",
        "Kenny Loggins - Danger Zone (Official Video - Top Gun).mp3",
        "Red Hot Chili Peppers - Snow (Hey Oh) (Official Music Video).mp3",
        "Metallica - The Unforgiven (Official Music Video).mp3",
        "Supertramp - The Logical Song (Official Video).mp3",
        "Cage The Elephant - Ain't No Rest For The Wicked (Official Video).mp3",
        "Arctic Monkeys - Old Yellow Bricks.mp3",
        "Young the Giant - Cough Syrup (Official Video).mp3",
        "Green Day - Boulevard Of Broken Dreams [Official Music Video] [4K Upgrade].mp3",
        "Led Zeppelin - Immigrant Song (Official Audio).mp3",
        "The Police - Every Breath You Take (Official Music Video).mp3",
        "Bruce Springsteen - Born to Run (Official Video).mp3",
        "Bon Jovi - It's My Life (Official Music Video).mp3",
        "Aerosmith - Love In An Elevator.mp3",
        "Steppenwolf - Magic Carpet Ride (Version 1969).mp3",
        "Neil Young - Old Man (Official Audio).mp3",
        "Sheryl Crow - Real Gone.mp3",
        "The Rolling Stones - Sympathy For The Devil (Official Lyric Video).mp3",
        "Bon Jovi - You Give Love A Bad Name.mp3",
        "Coldplay - Viva La Vida (Official Video).mp3",
        "Rush - Tom Sawyer.mp3",
        "The Cranberries - Zombie (Official Music Video).mp3",
        "Led Zeppelin - Kashmir (Remaster) (Official Audio).mp3",
        "The Police - Don't Stand So Close To Me (Official Music Video).mp3",
        "Al Stewart - Valentina Way.mp3",
        "Blind Melon - No Rain.mp3",
        "Breakbot - Baby I'm Yours (feat. Irfane) [Official Video].mp3",
        "Sure Sure - Funky Galileo (Very Official Music Video).mp3",
        "Young the Giant - My Body (Official Video).mp3",
        "Electric Light Orchestra - Sweet Talkin' Woman (Audio).mp3",
        "Blue Oyster Cult - Sole Survivor.mp3",
    ],
    "b-tier":
    [
        "Nat King Cole - Love Me As Though There Were No Tomorrow.mp3",
        "The Weeknd - Blinding Lights.mp3",
        "Gordon Lightfoot - Long River (1966).mp3",
        "Paul McCartney - Nineteen Hundred And Eighty-Five.mp3",
        "The Beatles - Eleanor Rigby (Official Music Video).mp3",
        "Peach Pit - Alrighty Aphrodite.mp3",
        "Gordon Lightfoot - High And Dry.mp3",
        "Gordon Lightfoot - Rainy Day People.mp3",
        "Metallica - Battery (HD).mp3",
        "Elton John - I Think I'm Gonna Kill Myself.mp3",
        "Gordon Lightfoot - Approaching Lavender (Lyrics).mp3",
        "Limp Bizkit - Break Stuff (Official Music Video).mp3",
        "Gordon Lightfoot - Beautiful (Lyrics) [HD].mp3",
        "John Hiatt - Over The Hill [Official Video].mp3",
        "The Beatles - You Never Give Me Your Money.mp3",
        "Jackson Browne - The Barricades Of Heaven.mp3",
        "Linkin Park - Somewhere I Belong.mp3",
        "Gordon Lightfoot - Summer Side of Life.mp3",
        "Gotye - Somebody That I Used To Know (feat. Kimbra) [Official Music Video].mp3",
        "The Drifters - This Magic Moment.mp3",
        "Foo Fighters - Cold Day In The Sun.mp3",
        "Phil Collins - Another Day In Paradise [Audio HQ] HD.mp3",
        "Gordon Lightfoot - The Canadian Railroad Trilogy.mp3",
        "Gordon Lightfoot - Don Quixote.mp3",
        "Pink Floyd - Breathe (In The Air) (2023 Remaster).mp3",
        "The Beatles - While My Guitar Gently Weeps.mp3",
        "TOOL - Sober (Official Video).mp3",
        "Gordon Lightfoot - Sit Down Young Stranger.mp3",
        "Gordon Lightfoot - Early Morning Rain.mp3",
        "Metallica - Enter Sandman.mp3",
        "Nickelback - Burn It to the Ground [OFFICIAL HD VIDEO].mp3",
    ],
};