const playlists =
{
    "s-tier":
    [
        "2Pac - Changes ft. Talent.mp3",
        "ABBA - Dancing Queen (Official Music Video).mp3",
        "Al Stewart - Year of the Cat (Official Audio).mp3",
        "Billy Joel - Modern Woman (Audio).mp3",
        "Billy Joel - Pressure (Official Video).mp3",
        "Billy Joel - Stiletto (Audio).mp3",
        "Blondie - Heart Of Glass.mp3",
        "Bon Jovi - Wanted Dead Or Alive (Official Music Video).mp3",
        "Bonnie Tyler - Holding Out For A Hero (Official HD Video).mp3",
        "Daft Punk - Get Lucky (Official Audio) ft. Pharrell Williams, Nile Rodgers.mp3",
        "David Bowie - Starman (Official Video) [4K].mp3",
        "Dexys Midnight Runners, Kevin Rowland - Come On Eileen (1982 Version).mp3",
        "Don McLean - American Pie (Lyric Video).mp3",
        "Eagles - New Kid In Town (Official Audio).mp3",
        "Fleetwood Mac - The Chain (Official Music Video) [HD].mp3",
        "Gordon Lightfoot - Sundown (Official Audio).mp3",
        "Gordon Lightfoot - Carefree Highway (1974).mp3",
        "Lenny Kravitz - Fly Away (Official Music Video).mp3",
        "MACKLEMORE & RYAN LEWIS - DOWNTOWN (OFFICIAL MUSIC VIDEO).mp3",
        "Merlin's Time - Al Stewart (studio).mp3",
        "Nickelback - How You Remind Me [OFFICIAL VIDEO].mp3",
        "Olivia Rodrigo - vampire (Official Video).mp3",
        "Pearl Jam - Jeremy (Official 4K Video).mp3",
        "Red Hot Chili Peppers - Californication (Official Music Video) [HD UPGRADE].mp3",
        "Tears For Fears - Everybody Wants To Rule The World (Official Music Video).mp3",
        "The Fuse.mp3",
        "The Pretender.mp3",
    ],
    "a-tier":
    [
        "ABBA - Gimme! Gimme! Gimme! (A Man After Midnight).mp3",
        "Fleetwood Mac - Dreams (Official Audio).mp3",
        "Gordon Lightfoot - Wreck Of The Edmund Fitzgerald (Official Audio).mp3",
        "Jamiroquai - Virtual Insanity (Official Music Video).mp3",
        "Nirvana - Lithium (Official Music Video).mp3",
        "Pearl Jam - Even Flow (Official Video).mp3",
        "Radiohead - Karma Police.mp3",
        "Stone Temple Pilots - Creep (Official Music Video).mp3",
        "Foo Fighters - All My Life (Official HD Video).mp3",
        "Foo Fighters - The Pretender.mp3",
        "Elton John - Goodbye Yellow Brick Road.mp3",
        "George Ezra - Budapest (Official Video).mp3",
        "Jackson Browne ~ Doctor, My Eyes 1972 (Official Promo) (Upgraded to stereo) (w_lyrics) [HD].mp3",
        "Jackson Browne - For America.mp3",
        "Billy Joel - Scenes from an Italian Restaurant (Audio).mp3",
        "Billy Joel - Sleeping with the Television On (Audio).mp3",
        "Eagles - One Of These Nights (Official Audio).mp3",
        "Don Henley - The Boys Of Summer.mp3",
        "Glenn Frey - You Belong To The City.mp3",
        "Sting - Be Still My Beating Heart.mp3",
        "Pearl Jam - Black (Official Audio).mp3",
        "Stompin' Tom Connors - Bud The Spud.mp3",
        "Foster The People - Lotus Eater (Audio).mp3",
        "The Smashing Pumpkins - 1979 (Official Music Video).mp3",
        "David Bowie - Young Americans.mp3",
        "David Bowie - Modern Love (Official Video) [HD].mp3",
        "Al Stewart - Night Train to Munich.mp3",
        "George Michael - Faith (Official Video).mp3",
        "Kenny Loggins - Danger Zone (Official Video - Top Gun).mp3",
        "Red Hot Chili Peppers - Snow (Hey Oh) (Official Music Video).mp3",
        "Metallica - The Unforgiven (Official Music Video).mp3",
        "Supertramp - The Logical Song (Official Video).mp3",
        "Cage The Elephant - Ain't No Rest For The Wicked (Official Video).mp3",
    ],
    
};